[package]
name = "salmiak"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-a = "2"
register = "0.2"
r0 = "0.2"

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"
